project_id = "achsqyusedhegqqgpucu"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
refresh_token_reuse_interval = 10
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_email_changes = true
enable_confirmations = false

[auth.jwt]
aud = "authenticated"
exp = 3600

[db]
port = 54322
shadow_port = 54320
major_version = 15

[storage]
enabled = true
file_size_limit = "50MiB"

[edge_functions]
enabled = true

[functions.complete-raffle]
verify_jwt = false

[functions.process-affiliate-bonus]
verify_jwt = false

[functions.paggue-webhook]
verify_jwt = false

[functions.weekly-affiliate-payout]
verify_jwt = false

[functions.get-affiliate-ranking]
verify_jwt = false

[functions.monthly-affiliate-payout]
verify_jwt = false

[analytics]
enabled = false